cabal-version:      3.0
name:               Frevo
version:            0.1.0.0
synopsis:           Linguagem de ensino com vocabulário pernambucano
license:            BSD-3-Clause
author:             ElissonXD
maintainer:         elissondias2006@gmail.com
build-type:         Simple

common shared
    ghc-options:      -Wall
    default-language: Haskell2010
    build-depends:    base >=4.18 && <5,
                      text >=2.1,
                      megaparsec

library
    import:           shared
    hs-source-dirs:   src
    exposed-modules:  Frevo.AST
                      Frevo.Lexer
                      Frevo.Parser
    build-depends:    parser-combinators

executable Frevo
    import:           shared
    hs-source-dirs:   app
    main-is:          Main.hs
    build-depends:    Frevo

test-suite spec
    import:           shared
    type:             exitcode-stdio-1.0
    hs-source-dirs:   test
    main-is:          Spec.hs
    other-modules:    Frevo.LexerSpec
                      Frevo.ExprSpec
                      Frevo.StmtSpec
                      Frevo.ErroSpec
    build-depends:    Frevo,
                      hspec
